#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 98
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 70
#define ALIAS_COUNT 0
#define TOKEN_COUNT 39
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7

enum {
  anon_sym_DOT = 1,
  sym_decimal = 2,
  anon_sym_e = 3,
  anon_sym_E = 4,
  anon_sym_PLUS = 5,
  anon_sym_DASH = 6,
  anon_sym_BANG = 7,
  anon_sym_STAR = 8,
  anon_sym_SLASH = 9,
  anon_sym_PERCENT = 10,
  anon_sym_EQ_EQ = 11,
  anon_sym_BANG_EQ = 12,
  anon_sym_LT = 13,
  anon_sym_GT = 14,
  anon_sym_LT_EQ = 15,
  anon_sym_GT_EQ = 16,
  anon_sym_PIPE_PIPE = 17,
  anon_sym_AMP_AMP = 18,
  anon_sym_foo = 19,
  anon_sym_EQ = 20,
  anon_sym_LPAREN = 21,
  anon_sym_RPAREN = 22,
  anon_sym_LBRACK = 23,
  anon_sym_RBRACK = 24,
  anon_sym_for = 25,
  anon_sym_COMMA = 26,
  anon_sym_in = 27,
  anon_sym_COLON = 28,
  anon_sym_if = 29,
  anon_sym_DOT_DOT_DOT = 30,
  anon_sym_LBRACE = 31,
  anon_sym_RBRACE = 32,
  anon_sym_DQUOTE = 33,
  aux_sym_stringLiteral_token1 = 34,
  sym_true = 35,
  sym_false = 36,
  sym_null = 37,
  sym_comment = 38,
  sym_body = 39,
  sym_numericLiteral = 40,
  sym_exponentMark = 41,
  sym_operation = 42,
  sym_unaryOp = 43,
  sym_binaryOp = 44,
  sym_binaryOperator = 45,
  sym_arithmeticOperator = 46,
  sym_compareOperator = 47,
  sym_logicOperator = 48,
  sym_attribute = 49,
  sym_block = 50,
  sym_expression = 51,
  sym_expressionTerm = 52,
  sym_forExpression = 53,
  sym_forTupleExpression = 54,
  sym_forIntro = 55,
  sym_forCondition = 56,
  sym_functionCall = 57,
  sym_arguments = 58,
  sym_collectionValue = 59,
  sym_tuple = 60,
  sym_object = 61,
  sym_objectElement = 62,
  sym_stringLiteral = 63,
  sym_literalValue = 64,
  aux_sym_body_repeat1 = 65,
  aux_sym_numericLiteral_repeat1 = 66,
  aux_sym_arguments_repeat1 = 67,
  aux_sym_object_repeat1 = 68,
  aux_sym_stringLiteral_repeat1 = 69,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DOT] = ".",
  [sym_decimal] = "decimal",
  [anon_sym_e] = "e",
  [anon_sym_E] = "E",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_BANG] = "!",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_foo] = "foo",
  [anon_sym_EQ] = "=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_for] = "for",
  [anon_sym_COMMA] = ",",
  [anon_sym_in] = "in",
  [anon_sym_COLON] = ":",
  [anon_sym_if] = "if",
  [anon_sym_DOT_DOT_DOT] = "...",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_stringLiteral_token1] = "stringLiteral_token1",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_null] = "null",
  [sym_comment] = "comment",
  [sym_body] = "body",
  [sym_numericLiteral] = "numericLiteral",
  [sym_exponentMark] = "exponentMark",
  [sym_operation] = "operation",
  [sym_unaryOp] = "unaryOp",
  [sym_binaryOp] = "binaryOp",
  [sym_binaryOperator] = "binaryOperator",
  [sym_arithmeticOperator] = "arithmeticOperator",
  [sym_compareOperator] = "compareOperator",
  [sym_logicOperator] = "logicOperator",
  [sym_attribute] = "attribute",
  [sym_block] = "block",
  [sym_expression] = "expression",
  [sym_expressionTerm] = "expressionTerm",
  [sym_forExpression] = "forExpression",
  [sym_forTupleExpression] = "forTupleExpression",
  [sym_forIntro] = "forIntro",
  [sym_forCondition] = "forCondition",
  [sym_functionCall] = "functionCall",
  [sym_arguments] = "arguments",
  [sym_collectionValue] = "collectionValue",
  [sym_tuple] = "tuple",
  [sym_object] = "object",
  [sym_objectElement] = "objectElement",
  [sym_stringLiteral] = "stringLiteral",
  [sym_literalValue] = "literalValue",
  [aux_sym_body_repeat1] = "body_repeat1",
  [aux_sym_numericLiteral_repeat1] = "numericLiteral_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
  [aux_sym_object_repeat1] = "object_repeat1",
  [aux_sym_stringLiteral_repeat1] = "stringLiteral_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_decimal] = sym_decimal,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_E] = anon_sym_E,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_foo] = anon_sym_foo,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_DOT_DOT_DOT] = anon_sym_DOT_DOT_DOT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_stringLiteral_token1] = aux_sym_stringLiteral_token1,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_null] = sym_null,
  [sym_comment] = sym_comment,
  [sym_body] = sym_body,
  [sym_numericLiteral] = sym_numericLiteral,
  [sym_exponentMark] = sym_exponentMark,
  [sym_operation] = sym_operation,
  [sym_unaryOp] = sym_unaryOp,
  [sym_binaryOp] = sym_binaryOp,
  [sym_binaryOperator] = sym_binaryOperator,
  [sym_arithmeticOperator] = sym_arithmeticOperator,
  [sym_compareOperator] = sym_compareOperator,
  [sym_logicOperator] = sym_logicOperator,
  [sym_attribute] = sym_attribute,
  [sym_block] = sym_block,
  [sym_expression] = sym_expression,
  [sym_expressionTerm] = sym_expressionTerm,
  [sym_forExpression] = sym_forExpression,
  [sym_forTupleExpression] = sym_forTupleExpression,
  [sym_forIntro] = sym_forIntro,
  [sym_forCondition] = sym_forCondition,
  [sym_functionCall] = sym_functionCall,
  [sym_arguments] = sym_arguments,
  [sym_collectionValue] = sym_collectionValue,
  [sym_tuple] = sym_tuple,
  [sym_object] = sym_object,
  [sym_objectElement] = sym_objectElement,
  [sym_stringLiteral] = sym_stringLiteral,
  [sym_literalValue] = sym_literalValue,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
  [aux_sym_numericLiteral_repeat1] = aux_sym_numericLiteral_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
  [aux_sym_stringLiteral_repeat1] = aux_sym_stringLiteral_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_decimal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_E] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_foo] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_stringLiteral_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_numericLiteral] = {
    .visible = true,
    .named = true,
  },
  [sym_exponentMark] = {
    .visible = true,
    .named = true,
  },
  [sym_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_unaryOp] = {
    .visible = true,
    .named = true,
  },
  [sym_binaryOp] = {
    .visible = true,
    .named = true,
  },
  [sym_binaryOperator] = {
    .visible = true,
    .named = true,
  },
  [sym_arithmeticOperator] = {
    .visible = true,
    .named = true,
  },
  [sym_compareOperator] = {
    .visible = true,
    .named = true,
  },
  [sym_logicOperator] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_expressionTerm] = {
    .visible = true,
    .named = true,
  },
  [sym_forExpression] = {
    .visible = true,
    .named = true,
  },
  [sym_forTupleExpression] = {
    .visible = true,
    .named = true,
  },
  [sym_forIntro] = {
    .visible = true,
    .named = true,
  },
  [sym_forCondition] = {
    .visible = true,
    .named = true,
  },
  [sym_functionCall] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_collectionValue] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_objectElement] = {
    .visible = true,
    .named = true,
  },
  [sym_stringLiteral] = {
    .visible = true,
    .named = true,
  },
  [sym_literalValue] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_numericLiteral_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_stringLiteral_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static TSSymbol ts_alias_sequences[1][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      if (lookahead == '!') ADVANCE(30);
      if (lookahead == '"') ADVANCE(56);
      if (lookahead == '#') ADVANCE(68);
      if (lookahead == '%') ADVANCE(33);
      if (lookahead == '&') ADVANCE(5);
      if (lookahead == '(') ADVANCE(44);
      if (lookahead == ')') ADVANCE(45);
      if (lookahead == '*') ADVANCE(31);
      if (lookahead == '+') ADVANCE(28);
      if (lookahead == ',') ADVANCE(49);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '.') ADVANCE(24);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == ':') ADVANCE(51);
      if (lookahead == '<') ADVANCE(36);
      if (lookahead == '=') ADVANCE(43);
      if (lookahead == '>') ADVANCE(37);
      if (lookahead == 'E') ADVANCE(27);
      if (lookahead == '[') ADVANCE(46);
      if (lookahead == ']') ADVANCE(47);
      if (lookahead == 'e') ADVANCE(26);
      if (lookahead == 'f') ADVANCE(10);
      if (lookahead == 'i') ADVANCE(13);
      if (lookahead == 'n') ADVANCE(21);
      if (lookahead == 't') ADVANCE(18);
      if (lookahead == '{') ADVANCE(54);
      if (lookahead == '|') ADVANCE(22);
      if (lookahead == '}') ADVANCE(55);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(4)
      if (lookahead == '"') ADVANCE(56);
      if (lookahead == '#') ADVANCE(62);
      if (lookahead == '/') ADVANCE(59);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(57);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '\r') ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(56);
      if (lookahead == '#') ADVANCE(68);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      END_STATE();
    case 5:
      if (lookahead == '&') ADVANCE(41);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(68);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(67);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(53);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(14);
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(65);
      END_STATE();
    case 13:
      if (lookahead == 'f') ADVANCE(52);
      if (lookahead == 'n') ADVANCE(50);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(66);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(42);
      if (lookahead == 'r') ADVANCE(48);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 19:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 20:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 21:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 22:
      if (lookahead == '|') ADVANCE(40);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(9);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_decimal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_e);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_E);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(35);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(68);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(38);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(39);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_foo);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(34);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_DOT_DOT_DOT);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_stringLiteral_token1);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_stringLiteral_token1);
      if (lookahead == '#') ADVANCE(62);
      if (lookahead == '/') ADVANCE(59);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(63);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_stringLiteral_token1);
      if (lookahead == '*') ADVANCE(61);
      if (lookahead == '/') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(63);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_stringLiteral_token1);
      if (lookahead == '*') ADVANCE(60);
      if (lookahead == '/') ADVANCE(63);
      if (lookahead == '\n' ||
          lookahead == '"' ||
          lookahead == '\\') ADVANCE(8);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_stringLiteral_token1);
      if (lookahead == '*') ADVANCE(60);
      if (lookahead == '\n' ||
          lookahead == '"' ||
          lookahead == '\\') ADVANCE(8);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_stringLiteral_token1);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_stringLiteral_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(68);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_decimal] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_E] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_foo] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_body] = STATE(97),
    [sym_attribute] = STATE(58),
    [sym_block] = STATE(58),
    [aux_sym_body_repeat1] = STATE(58),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_foo] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(13), 1,
      sym_decimal,
    STATE(3), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(80), 1,
      sym_exponentMark,
    ACTIONS(15), 2,
      anon_sym_e,
      anon_sym_E,
    ACTIONS(17), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(9), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [48] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      sym_decimal,
    STATE(3), 1,
      aux_sym_numericLiteral_repeat1,
    ACTIONS(21), 6,
      anon_sym_DOT,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(19), 21,
      ts_builtin_sym_end,
      anon_sym_e,
      anon_sym_E,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [89] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_decimal,
    STATE(3), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(82), 1,
      sym_exponentMark,
    ACTIONS(15), 2,
      anon_sym_e,
      anon_sym_E,
    ACTIONS(28), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(26), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [134] = 21,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      sym_decimal,
    ACTIONS(34), 1,
      anon_sym_foo,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_LBRACK,
    ACTIONS(40), 1,
      anon_sym_RBRACK,
    ACTIONS(42), 1,
      anon_sym_for,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(10), 1,
      sym_expressionTerm,
    STATE(25), 1,
      sym_forIntro,
    STATE(35), 1,
      sym_numericLiteral,
    STATE(40), 1,
      sym_forTupleExpression,
    STATE(51), 1,
      sym_operation,
    STATE(67), 1,
      sym_expression,
    ACTIONS(32), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(44), 2,
      sym_tuple,
      sym_object,
    STATE(50), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(48), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(38), 5,
      sym_forExpression,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [207] = 20,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      sym_decimal,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    ACTIONS(50), 1,
      anon_sym_foo,
    ACTIONS(52), 1,
      anon_sym_RBRACE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(10), 1,
      sym_expressionTerm,
    STATE(35), 1,
      sym_numericLiteral,
    STATE(40), 1,
      sym_forTupleExpression,
    STATE(51), 1,
      sym_operation,
    STATE(78), 1,
      sym_expression,
    STATE(79), 1,
      sym_objectElement,
    ACTIONS(32), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(44), 2,
      sym_tuple,
      sym_object,
    STATE(50), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(48), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(38), 5,
      sym_forExpression,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [277] = 20,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      sym_decimal,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    ACTIONS(50), 1,
      anon_sym_foo,
    ACTIONS(54), 1,
      anon_sym_RBRACE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(10), 1,
      sym_expressionTerm,
    STATE(35), 1,
      sym_numericLiteral,
    STATE(40), 1,
      sym_forTupleExpression,
    STATE(51), 1,
      sym_operation,
    STATE(78), 1,
      sym_expression,
    STATE(79), 1,
      sym_objectElement,
    ACTIONS(32), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(44), 2,
      sym_tuple,
      sym_object,
    STATE(50), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(48), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(38), 5,
      sym_forExpression,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [347] = 20,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      sym_decimal,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    ACTIONS(50), 1,
      anon_sym_foo,
    ACTIONS(56), 1,
      anon_sym_RBRACE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(10), 1,
      sym_expressionTerm,
    STATE(35), 1,
      sym_numericLiteral,
    STATE(40), 1,
      sym_forTupleExpression,
    STATE(51), 1,
      sym_operation,
    STATE(63), 1,
      sym_objectElement,
    STATE(78), 1,
      sym_expression,
    ACTIONS(32), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(44), 2,
      sym_tuple,
      sym_object,
    STATE(50), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(48), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(38), 5,
      sym_forExpression,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [417] = 20,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      sym_decimal,
    ACTIONS(34), 1,
      anon_sym_foo,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    ACTIONS(58), 1,
      anon_sym_RPAREN,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(10), 1,
      sym_expressionTerm,
    STATE(35), 1,
      sym_numericLiteral,
    STATE(40), 1,
      sym_forTupleExpression,
    STATE(51), 1,
      sym_operation,
    STATE(61), 1,
      sym_expression,
    STATE(94), 1,
      sym_arguments,
    ACTIONS(32), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(44), 2,
      sym_tuple,
      sym_object,
    STATE(50), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(48), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(38), 5,
      sym_forExpression,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [487] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_BANG,
    ACTIONS(66), 1,
      anon_sym_SLASH,
    ACTIONS(74), 1,
      anon_sym_EQ,
    STATE(46), 1,
      sym_binaryOperator,
    ACTIONS(70), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(72), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
    STATE(53), 3,
      sym_arithmeticOperator,
      sym_compareOperator,
      sym_logicOperator,
    ACTIONS(62), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(68), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(60), 9,
      ts_builtin_sym_end,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [539] = 19,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      sym_decimal,
    ACTIONS(34), 1,
      anon_sym_foo,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    ACTIONS(76), 1,
      anon_sym_RPAREN,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(10), 1,
      sym_expressionTerm,
    STATE(35), 1,
      sym_numericLiteral,
    STATE(40), 1,
      sym_forTupleExpression,
    STATE(51), 1,
      sym_operation,
    STATE(62), 1,
      sym_expression,
    ACTIONS(32), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(44), 2,
      sym_tuple,
      sym_object,
    STATE(50), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(48), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(38), 5,
      sym_forExpression,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [606] = 19,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      sym_decimal,
    ACTIONS(34), 1,
      anon_sym_foo,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    ACTIONS(78), 1,
      anon_sym_RBRACK,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(10), 1,
      sym_expressionTerm,
    STATE(35), 1,
      sym_numericLiteral,
    STATE(40), 1,
      sym_forTupleExpression,
    STATE(51), 1,
      sym_operation,
    STATE(62), 1,
      sym_expression,
    ACTIONS(32), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(44), 2,
      sym_tuple,
      sym_object,
    STATE(50), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(48), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(38), 5,
      sym_forExpression,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [673] = 19,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      sym_decimal,
    ACTIONS(34), 1,
      anon_sym_foo,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    ACTIONS(80), 1,
      anon_sym_RPAREN,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(10), 1,
      sym_expressionTerm,
    STATE(35), 1,
      sym_numericLiteral,
    STATE(40), 1,
      sym_forTupleExpression,
    STATE(51), 1,
      sym_operation,
    STATE(62), 1,
      sym_expression,
    ACTIONS(32), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(44), 2,
      sym_tuple,
      sym_object,
    STATE(50), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(48), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(38), 5,
      sym_forExpression,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [740] = 19,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      sym_decimal,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    ACTIONS(50), 1,
      anon_sym_foo,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(10), 1,
      sym_expressionTerm,
    STATE(35), 1,
      sym_numericLiteral,
    STATE(40), 1,
      sym_forTupleExpression,
    STATE(51), 1,
      sym_operation,
    STATE(78), 1,
      sym_expression,
    STATE(79), 1,
      sym_objectElement,
    ACTIONS(32), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(44), 2,
      sym_tuple,
      sym_object,
    STATE(50), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(48), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(38), 5,
      sym_forExpression,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [807] = 19,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      sym_decimal,
    ACTIONS(34), 1,
      anon_sym_foo,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    ACTIONS(82), 1,
      anon_sym_RBRACK,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(10), 1,
      sym_expressionTerm,
    STATE(35), 1,
      sym_numericLiteral,
    STATE(40), 1,
      sym_forTupleExpression,
    STATE(51), 1,
      sym_operation,
    STATE(62), 1,
      sym_expression,
    ACTIONS(32), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(44), 2,
      sym_tuple,
      sym_object,
    STATE(50), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(48), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(38), 5,
      sym_forExpression,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [874] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      sym_decimal,
    ACTIONS(34), 1,
      anon_sym_foo,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(10), 1,
      sym_expressionTerm,
    STATE(35), 1,
      sym_numericLiteral,
    STATE(40), 1,
      sym_forTupleExpression,
    STATE(51), 1,
      sym_operation,
    STATE(86), 1,
      sym_expression,
    ACTIONS(32), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(44), 2,
      sym_tuple,
      sym_object,
    STATE(50), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(48), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(38), 5,
      sym_forExpression,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [938] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      sym_decimal,
    ACTIONS(34), 1,
      anon_sym_foo,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(10), 1,
      sym_expressionTerm,
    STATE(35), 1,
      sym_numericLiteral,
    STATE(40), 1,
      sym_forTupleExpression,
    STATE(51), 1,
      sym_operation,
    STATE(89), 1,
      sym_expression,
    ACTIONS(32), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(44), 2,
      sym_tuple,
      sym_object,
    STATE(50), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(48), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(38), 5,
      sym_forExpression,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [1002] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      sym_decimal,
    ACTIONS(34), 1,
      anon_sym_foo,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(10), 1,
      sym_expressionTerm,
    STATE(35), 1,
      sym_numericLiteral,
    STATE(40), 1,
      sym_forTupleExpression,
    STATE(51), 1,
      sym_operation,
    STATE(77), 1,
      sym_expression,
    ACTIONS(32), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(44), 2,
      sym_tuple,
      sym_object,
    STATE(50), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(48), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(38), 5,
      sym_forExpression,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [1066] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      sym_decimal,
    ACTIONS(34), 1,
      anon_sym_foo,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(10), 1,
      sym_expressionTerm,
    STATE(35), 1,
      sym_numericLiteral,
    STATE(40), 1,
      sym_forTupleExpression,
    STATE(51), 1,
      sym_operation,
    STATE(96), 1,
      sym_expression,
    ACTIONS(32), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(44), 2,
      sym_tuple,
      sym_object,
    STATE(50), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(48), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(38), 5,
      sym_forExpression,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [1130] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_decimal,
    STATE(3), 1,
      aux_sym_numericLiteral_repeat1,
    ACTIONS(28), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(26), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [1168] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      sym_decimal,
    ACTIONS(34), 1,
      anon_sym_foo,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(10), 1,
      sym_expressionTerm,
    STATE(35), 1,
      sym_numericLiteral,
    STATE(40), 1,
      sym_forTupleExpression,
    STATE(51), 1,
      sym_operation,
    STATE(62), 1,
      sym_expression,
    ACTIONS(32), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(44), 2,
      sym_tuple,
      sym_object,
    STATE(50), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(48), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(38), 5,
      sym_forExpression,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [1232] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_decimal,
    STATE(3), 1,
      aux_sym_numericLiteral_repeat1,
    ACTIONS(86), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(84), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [1270] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      sym_decimal,
    ACTIONS(34), 1,
      anon_sym_foo,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(10), 1,
      sym_expressionTerm,
    STATE(35), 1,
      sym_numericLiteral,
    STATE(40), 1,
      sym_forTupleExpression,
    STATE(51), 1,
      sym_operation,
    STATE(83), 1,
      sym_expression,
    ACTIONS(32), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(44), 2,
      sym_tuple,
      sym_object,
    STATE(50), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(48), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(38), 5,
      sym_forExpression,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [1334] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      sym_decimal,
    ACTIONS(34), 1,
      anon_sym_foo,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(10), 1,
      sym_expressionTerm,
    STATE(35), 1,
      sym_numericLiteral,
    STATE(40), 1,
      sym_forTupleExpression,
    STATE(51), 1,
      sym_operation,
    STATE(88), 1,
      sym_expression,
    ACTIONS(32), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(44), 2,
      sym_tuple,
      sym_object,
    STATE(50), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(48), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(38), 5,
      sym_forExpression,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [1398] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      sym_decimal,
    ACTIONS(34), 1,
      anon_sym_foo,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(10), 1,
      sym_expressionTerm,
    STATE(35), 1,
      sym_numericLiteral,
    STATE(40), 1,
      sym_forTupleExpression,
    STATE(51), 1,
      sym_operation,
    STATE(70), 1,
      sym_expression,
    ACTIONS(32), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(44), 2,
      sym_tuple,
      sym_object,
    STATE(50), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(48), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(38), 5,
      sym_forExpression,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [1462] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(88), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [1494] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(92), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [1526] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(96), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [1558] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(100), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [1590] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(104), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [1622] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(108), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [1654] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(112), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [1686] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(116), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [1718] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(120), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [1750] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(124), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [1782] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(128), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [1814] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(132), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [1846] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(136), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [1878] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(140), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [1910] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(144), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [1942] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(148), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [1974] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(152), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [2006] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(156), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [2038] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(160), 19,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [2070] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      sym_decimal,
    ACTIONS(34), 1,
      anon_sym_foo,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(35), 1,
      sym_numericLiteral,
    STATE(40), 1,
      sym_forTupleExpression,
    STATE(49), 1,
      sym_expressionTerm,
    STATE(44), 2,
      sym_tuple,
      sym_object,
    ACTIONS(48), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(38), 5,
      sym_forExpression,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [2120] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      sym_decimal,
    ACTIONS(34), 1,
      anon_sym_foo,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(35), 1,
      sym_numericLiteral,
    STATE(40), 1,
      sym_forTupleExpression,
    STATE(52), 1,
      sym_expressionTerm,
    STATE(44), 2,
      sym_tuple,
      sym_object,
    ACTIONS(48), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(38), 5,
      sym_forExpression,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [2170] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 11,
      sym_decimal,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_foo,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      sym_null,
  [2187] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 11,
      sym_decimal,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_foo,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      sym_null,
  [2204] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 10,
      ts_builtin_sym_end,
      anon_sym_foo,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [2220] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 10,
      ts_builtin_sym_end,
      anon_sym_foo,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [2236] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 10,
      ts_builtin_sym_end,
      anon_sym_foo,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [2252] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 10,
      ts_builtin_sym_end,
      anon_sym_foo,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_if,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACE,
  [2268] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 9,
      sym_decimal,
      anon_sym_foo,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      sym_null,
  [2283] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 9,
      sym_decimal,
      anon_sym_foo,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      sym_null,
  [2298] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 9,
      sym_decimal,
      anon_sym_foo,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      sym_null,
  [2313] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 9,
      sym_decimal,
      anon_sym_foo,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      sym_null,
  [2328] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      aux_sym_arguments_repeat1,
    ACTIONS(182), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_DOT_DOT_DOT,
  [2343] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_foo,
    ACTIONS(187), 1,
      ts_builtin_sym_end,
    STATE(59), 3,
      sym_attribute,
      sym_block,
      aux_sym_body_repeat1,
  [2358] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      ts_builtin_sym_end,
    ACTIONS(191), 1,
      anon_sym_foo,
    STATE(59), 3,
      sym_attribute,
      sym_block,
      aux_sym_body_repeat1,
  [2373] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_RPAREN,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    ACTIONS(196), 1,
      anon_sym_DOT_DOT_DOT,
    STATE(57), 1,
      aux_sym_arguments_repeat1,
  [2389] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      anon_sym_RPAREN,
    ACTIONS(200), 1,
      anon_sym_COMMA,
    ACTIONS(202), 1,
      anon_sym_DOT_DOT_DOT,
    STATE(60), 1,
      aux_sym_arguments_repeat1,
  [2405] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 4,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
  [2415] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_COMMA,
    ACTIONS(206), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      aux_sym_object_repeat1,
  [2428] = 4,
    ACTIONS(208), 1,
      anon_sym_DQUOTE,
    ACTIONS(210), 1,
      aux_sym_stringLiteral_token1,
    ACTIONS(213), 1,
      sym_comment,
    STATE(64), 1,
      aux_sym_stringLiteral_repeat1,
  [2441] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_RBRACK,
    ACTIONS(215), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      aux_sym_arguments_repeat1,
  [2454] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      anon_sym_RBRACE,
    ACTIONS(217), 1,
      anon_sym_COMMA,
    STATE(68), 1,
      aux_sym_object_repeat1,
  [2467] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      anon_sym_RBRACK,
    ACTIONS(221), 1,
      anon_sym_COMMA,
    STATE(65), 1,
      aux_sym_arguments_repeat1,
  [2480] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(226), 1,
      anon_sym_RBRACE,
    STATE(68), 1,
      aux_sym_object_repeat1,
  [2493] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_LPAREN,
    ACTIONS(228), 2,
      anon_sym_EQ,
      anon_sym_COLON,
  [2504] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_RBRACK,
    ACTIONS(234), 1,
      anon_sym_if,
    STATE(93), 1,
      sym_forCondition,
  [2517] = 4,
    ACTIONS(213), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_DQUOTE,
    ACTIONS(238), 1,
      aux_sym_stringLiteral_token1,
    STATE(73), 1,
      aux_sym_stringLiteral_repeat1,
  [2530] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      sym_decimal,
    ACTIONS(242), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [2541] = 4,
    ACTIONS(213), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_DQUOTE,
    ACTIONS(246), 1,
      aux_sym_stringLiteral_token1,
    STATE(64), 1,
      aux_sym_stringLiteral_repeat1,
  [2554] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_COMMA,
    ACTIONS(250), 1,
      anon_sym_in,
  [2564] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      sym_decimal,
    STATE(4), 1,
      aux_sym_numericLiteral_repeat1,
  [2574] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_foo,
    ACTIONS(256), 1,
      anon_sym_EQ,
  [2584] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2592] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 2,
      anon_sym_EQ,
      anon_sym_COLON,
  [2600] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2608] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      sym_decimal,
    STATE(20), 1,
      aux_sym_numericLiteral_repeat1,
  [2618] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 2,
      ts_builtin_sym_end,
      anon_sym_foo,
  [2626] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      sym_decimal,
    STATE(22), 1,
      aux_sym_numericLiteral_repeat1,
  [2636] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 2,
      ts_builtin_sym_end,
      anon_sym_foo,
  [2644] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_foo,
  [2651] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_in,
  [2658] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_COLON,
  [2665] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      anon_sym_foo,
  [2672] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      anon_sym_RPAREN,
  [2679] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      anon_sym_RBRACK,
  [2686] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_RPAREN,
  [2693] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      sym_decimal,
  [2700] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_LPAREN,
  [2707] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      anon_sym_RBRACK,
  [2714] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      anon_sym_RPAREN,
  [2721] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_RPAREN,
  [2728] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      anon_sym_COLON,
  [2735] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      ts_builtin_sym_end,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 48,
  [SMALL_STATE(4)] = 89,
  [SMALL_STATE(5)] = 134,
  [SMALL_STATE(6)] = 207,
  [SMALL_STATE(7)] = 277,
  [SMALL_STATE(8)] = 347,
  [SMALL_STATE(9)] = 417,
  [SMALL_STATE(10)] = 487,
  [SMALL_STATE(11)] = 539,
  [SMALL_STATE(12)] = 606,
  [SMALL_STATE(13)] = 673,
  [SMALL_STATE(14)] = 740,
  [SMALL_STATE(15)] = 807,
  [SMALL_STATE(16)] = 874,
  [SMALL_STATE(17)] = 938,
  [SMALL_STATE(18)] = 1002,
  [SMALL_STATE(19)] = 1066,
  [SMALL_STATE(20)] = 1130,
  [SMALL_STATE(21)] = 1168,
  [SMALL_STATE(22)] = 1232,
  [SMALL_STATE(23)] = 1270,
  [SMALL_STATE(24)] = 1334,
  [SMALL_STATE(25)] = 1398,
  [SMALL_STATE(26)] = 1462,
  [SMALL_STATE(27)] = 1494,
  [SMALL_STATE(28)] = 1526,
  [SMALL_STATE(29)] = 1558,
  [SMALL_STATE(30)] = 1590,
  [SMALL_STATE(31)] = 1622,
  [SMALL_STATE(32)] = 1654,
  [SMALL_STATE(33)] = 1686,
  [SMALL_STATE(34)] = 1718,
  [SMALL_STATE(35)] = 1750,
  [SMALL_STATE(36)] = 1782,
  [SMALL_STATE(37)] = 1814,
  [SMALL_STATE(38)] = 1846,
  [SMALL_STATE(39)] = 1878,
  [SMALL_STATE(40)] = 1910,
  [SMALL_STATE(41)] = 1942,
  [SMALL_STATE(42)] = 1974,
  [SMALL_STATE(43)] = 2006,
  [SMALL_STATE(44)] = 2038,
  [SMALL_STATE(45)] = 2070,
  [SMALL_STATE(46)] = 2120,
  [SMALL_STATE(47)] = 2170,
  [SMALL_STATE(48)] = 2187,
  [SMALL_STATE(49)] = 2204,
  [SMALL_STATE(50)] = 2220,
  [SMALL_STATE(51)] = 2236,
  [SMALL_STATE(52)] = 2252,
  [SMALL_STATE(53)] = 2268,
  [SMALL_STATE(54)] = 2283,
  [SMALL_STATE(55)] = 2298,
  [SMALL_STATE(56)] = 2313,
  [SMALL_STATE(57)] = 2328,
  [SMALL_STATE(58)] = 2343,
  [SMALL_STATE(59)] = 2358,
  [SMALL_STATE(60)] = 2373,
  [SMALL_STATE(61)] = 2389,
  [SMALL_STATE(62)] = 2405,
  [SMALL_STATE(63)] = 2415,
  [SMALL_STATE(64)] = 2428,
  [SMALL_STATE(65)] = 2441,
  [SMALL_STATE(66)] = 2454,
  [SMALL_STATE(67)] = 2467,
  [SMALL_STATE(68)] = 2480,
  [SMALL_STATE(69)] = 2493,
  [SMALL_STATE(70)] = 2504,
  [SMALL_STATE(71)] = 2517,
  [SMALL_STATE(72)] = 2530,
  [SMALL_STATE(73)] = 2541,
  [SMALL_STATE(74)] = 2554,
  [SMALL_STATE(75)] = 2564,
  [SMALL_STATE(76)] = 2574,
  [SMALL_STATE(77)] = 2584,
  [SMALL_STATE(78)] = 2592,
  [SMALL_STATE(79)] = 2600,
  [SMALL_STATE(80)] = 2608,
  [SMALL_STATE(81)] = 2618,
  [SMALL_STATE(82)] = 2626,
  [SMALL_STATE(83)] = 2636,
  [SMALL_STATE(84)] = 2644,
  [SMALL_STATE(85)] = 2651,
  [SMALL_STATE(86)] = 2658,
  [SMALL_STATE(87)] = 2665,
  [SMALL_STATE(88)] = 2672,
  [SMALL_STATE(89)] = 2679,
  [SMALL_STATE(90)] = 2686,
  [SMALL_STATE(91)] = 2693,
  [SMALL_STATE(92)] = 2700,
  [SMALL_STATE(93)] = 2707,
  [SMALL_STATE(94)] = 2714,
  [SMALL_STATE(95)] = 2721,
  [SMALL_STATE(96)] = 2728,
  [SMALL_STATE(97)] = 2735,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_numericLiteral, 1),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_numericLiteral, 1),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_numericLiteral_repeat1, 2),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_numericLiteral_repeat1, 2),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_numericLiteral_repeat1, 2), SHIFT_REPEAT(3),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_numericLiteral, 3),
  [28] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_numericLiteral, 3),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_numericLiteral, 5),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_numericLiteral, 5),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 2),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple, 2),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 5),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 5),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 5),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple, 5),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_forTupleExpression, 5),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_forTupleExpression, 5),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stringLiteral, 3),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stringLiteral, 3),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 4),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 2),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_forTupleExpression, 4),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_forTupleExpression, 4),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stringLiteral, 2),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stringLiteral, 2),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literalValue, 1),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literalValue, 1),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 3),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 3),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple, 3),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expressionTerm, 1),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expressionTerm, 1),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expressionTerm, 3),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expressionTerm, 3),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_forExpression, 1),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_forExpression, 1),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functionCall, 4),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functionCall, 4),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 4),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple, 4),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functionCall, 3),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functionCall, 3),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_collectionValue, 1),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_collectionValue, 1),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_forIntro, 5),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_forIntro, 7),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unaryOp, 2),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 1),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binaryOp, 3),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binaryOperator, 1),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compareOperator, 1),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logicOperator, 1),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arithmeticOperator, 1),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2),
  [184] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2), SHIFT_REPEAT(21),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2),
  [191] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2), SHIFT_REPEAT(76),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 1),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_stringLiteral_repeat1, 2),
  [210] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_stringLiteral_repeat1, 2), SHIFT_REPEAT(64),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [223] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2), SHIFT_REPEAT(14),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [236] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exponentMark, 1),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [246] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_objectElement, 3),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_forCondition, 2),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exponentMark, 2),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [288] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_hcl(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .field_count = FIELD_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
