#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 80
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 63
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5

enum {
  anon_sym_DOT = 1,
  sym_decimal = 2,
  anon_sym_e = 3,
  anon_sym_E = 4,
  anon_sym_PLUS = 5,
  anon_sym_DASH = 6,
  anon_sym_BANG = 7,
  anon_sym_STAR = 8,
  anon_sym_SLASH = 9,
  anon_sym_PERCENT = 10,
  anon_sym_EQ_EQ = 11,
  anon_sym_BANG_EQ = 12,
  anon_sym_LT = 13,
  anon_sym_GT = 14,
  anon_sym_LT_EQ = 15,
  anon_sym_GT_EQ = 16,
  anon_sym_PIPE_PIPE = 17,
  anon_sym_AMP_AMP = 18,
  anon_sym_foo = 19,
  anon_sym_EQ = 20,
  anon_sym_LPAREN = 21,
  anon_sym_RPAREN = 22,
  anon_sym_COMMA = 23,
  anon_sym_DOT_DOT_DOT = 24,
  anon_sym_LBRACK = 25,
  anon_sym_RBRACK = 26,
  anon_sym_LBRACE = 27,
  anon_sym_RBRACE = 28,
  anon_sym_COLON = 29,
  anon_sym_DQUOTE = 30,
  aux_sym_stringLiteral_token1 = 31,
  sym_true = 32,
  sym_false = 33,
  sym_null = 34,
  sym_comment = 35,
  sym_body = 36,
  sym_numericLiteral = 37,
  sym_exponentMark = 38,
  sym_operation = 39,
  sym_unaryOp = 40,
  sym_binaryOp = 41,
  sym_binaryOperator = 42,
  sym_arithmeticOperator = 43,
  sym_compareOperator = 44,
  sym_logicOperator = 45,
  sym_attribute = 46,
  sym_block = 47,
  sym_expression = 48,
  sym_expressionTerm = 49,
  sym_functionCall = 50,
  sym_arguments = 51,
  sym_collectionValue = 52,
  sym_tuple = 53,
  sym_object = 54,
  sym_objectElement = 55,
  sym_stringLiteral = 56,
  sym_literalValue = 57,
  aux_sym_body_repeat1 = 58,
  aux_sym_numericLiteral_repeat1 = 59,
  aux_sym_arguments_repeat1 = 60,
  aux_sym_object_repeat1 = 61,
  aux_sym_stringLiteral_repeat1 = 62,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DOT] = ".",
  [sym_decimal] = "decimal",
  [anon_sym_e] = "e",
  [anon_sym_E] = "E",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_BANG] = "!",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_foo] = "foo",
  [anon_sym_EQ] = "=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT_DOT_DOT] = "...",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_stringLiteral_token1] = "stringLiteral_token1",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_null] = "null",
  [sym_comment] = "comment",
  [sym_body] = "body",
  [sym_numericLiteral] = "numericLiteral",
  [sym_exponentMark] = "exponentMark",
  [sym_operation] = "operation",
  [sym_unaryOp] = "unaryOp",
  [sym_binaryOp] = "binaryOp",
  [sym_binaryOperator] = "binaryOperator",
  [sym_arithmeticOperator] = "arithmeticOperator",
  [sym_compareOperator] = "compareOperator",
  [sym_logicOperator] = "logicOperator",
  [sym_attribute] = "attribute",
  [sym_block] = "block",
  [sym_expression] = "expression",
  [sym_expressionTerm] = "expressionTerm",
  [sym_functionCall] = "functionCall",
  [sym_arguments] = "arguments",
  [sym_collectionValue] = "collectionValue",
  [sym_tuple] = "tuple",
  [sym_object] = "object",
  [sym_objectElement] = "objectElement",
  [sym_stringLiteral] = "stringLiteral",
  [sym_literalValue] = "literalValue",
  [aux_sym_body_repeat1] = "body_repeat1",
  [aux_sym_numericLiteral_repeat1] = "numericLiteral_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
  [aux_sym_object_repeat1] = "object_repeat1",
  [aux_sym_stringLiteral_repeat1] = "stringLiteral_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_decimal] = sym_decimal,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_E] = anon_sym_E,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_foo] = anon_sym_foo,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT_DOT_DOT] = anon_sym_DOT_DOT_DOT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_stringLiteral_token1] = aux_sym_stringLiteral_token1,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_null] = sym_null,
  [sym_comment] = sym_comment,
  [sym_body] = sym_body,
  [sym_numericLiteral] = sym_numericLiteral,
  [sym_exponentMark] = sym_exponentMark,
  [sym_operation] = sym_operation,
  [sym_unaryOp] = sym_unaryOp,
  [sym_binaryOp] = sym_binaryOp,
  [sym_binaryOperator] = sym_binaryOperator,
  [sym_arithmeticOperator] = sym_arithmeticOperator,
  [sym_compareOperator] = sym_compareOperator,
  [sym_logicOperator] = sym_logicOperator,
  [sym_attribute] = sym_attribute,
  [sym_block] = sym_block,
  [sym_expression] = sym_expression,
  [sym_expressionTerm] = sym_expressionTerm,
  [sym_functionCall] = sym_functionCall,
  [sym_arguments] = sym_arguments,
  [sym_collectionValue] = sym_collectionValue,
  [sym_tuple] = sym_tuple,
  [sym_object] = sym_object,
  [sym_objectElement] = sym_objectElement,
  [sym_stringLiteral] = sym_stringLiteral,
  [sym_literalValue] = sym_literalValue,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
  [aux_sym_numericLiteral_repeat1] = aux_sym_numericLiteral_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
  [aux_sym_stringLiteral_repeat1] = aux_sym_stringLiteral_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_decimal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_E] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_foo] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_stringLiteral_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_numericLiteral] = {
    .visible = true,
    .named = true,
  },
  [sym_exponentMark] = {
    .visible = true,
    .named = true,
  },
  [sym_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_unaryOp] = {
    .visible = true,
    .named = true,
  },
  [sym_binaryOp] = {
    .visible = true,
    .named = true,
  },
  [sym_binaryOperator] = {
    .visible = true,
    .named = true,
  },
  [sym_arithmeticOperator] = {
    .visible = true,
    .named = true,
  },
  [sym_compareOperator] = {
    .visible = true,
    .named = true,
  },
  [sym_logicOperator] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_expressionTerm] = {
    .visible = true,
    .named = true,
  },
  [sym_functionCall] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_collectionValue] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_objectElement] = {
    .visible = true,
    .named = true,
  },
  [sym_stringLiteral] = {
    .visible = true,
    .named = true,
  },
  [sym_literalValue] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_numericLiteral_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_stringLiteral_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static TSSymbol ts_alias_sequences[1][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(22);
      if (lookahead == '!') ADVANCE(29);
      if (lookahead == '"') ADVANCE(52);
      if (lookahead == '#') ADVANCE(64);
      if (lookahead == '%') ADVANCE(32);
      if (lookahead == '&') ADVANCE(5);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == ')') ADVANCE(44);
      if (lookahead == '*') ADVANCE(30);
      if (lookahead == '+') ADVANCE(27);
      if (lookahead == ',') ADVANCE(45);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == ':') ADVANCE(51);
      if (lookahead == '<') ADVANCE(35);
      if (lookahead == '=') ADVANCE(42);
      if (lookahead == '>') ADVANCE(36);
      if (lookahead == 'E') ADVANCE(26);
      if (lookahead == '[') ADVANCE(47);
      if (lookahead == ']') ADVANCE(48);
      if (lookahead == 'e') ADVANCE(25);
      if (lookahead == 'f') ADVANCE(10);
      if (lookahead == 'n') ADVANCE(20);
      if (lookahead == 't') ADVANCE(17);
      if (lookahead == '{') ADVANCE(49);
      if (lookahead == '|') ADVANCE(21);
      if (lookahead == '}') ADVANCE(50);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(4)
      if (lookahead == '"') ADVANCE(52);
      if (lookahead == '#') ADVANCE(58);
      if (lookahead == '/') ADVANCE(55);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(54);
      if (lookahead != 0) ADVANCE(59);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(53);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == '\r') ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(52);
      if (lookahead == '#') ADVANCE(64);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      END_STATE();
    case 5:
      if (lookahead == '&') ADVANCE(40);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(64);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(63);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(46);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(13);
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(62);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(41);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 19:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 20:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 21:
      if (lookahead == '|') ADVANCE(39);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(9);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_decimal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_e);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_E);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(34);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(64);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(38);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_foo);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(33);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DOT_DOT_DOT);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_stringLiteral_token1);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_stringLiteral_token1);
      if (lookahead == '#') ADVANCE(58);
      if (lookahead == '/') ADVANCE(55);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(59);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_stringLiteral_token1);
      if (lookahead == '*') ADVANCE(57);
      if (lookahead == '/') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(59);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_stringLiteral_token1);
      if (lookahead == '*') ADVANCE(56);
      if (lookahead == '/') ADVANCE(59);
      if (lookahead == '\n' ||
          lookahead == '"' ||
          lookahead == '\\') ADVANCE(8);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_stringLiteral_token1);
      if (lookahead == '*') ADVANCE(56);
      if (lookahead == '\n' ||
          lookahead == '"' ||
          lookahead == '\\') ADVANCE(8);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_stringLiteral_token1);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_stringLiteral_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_decimal] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_E] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_foo] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_body] = STATE(79),
    [sym_attribute] = STATE(49),
    [sym_block] = STATE(49),
    [aux_sym_body_repeat1] = STATE(49),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_foo] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(13), 1,
      sym_decimal,
    STATE(3), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(68), 1,
      sym_exponentMark,
    ACTIONS(15), 2,
      anon_sym_e,
      anon_sym_E,
    ACTIONS(17), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(9), 18,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [47] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      sym_decimal,
    STATE(3), 1,
      aux_sym_numericLiteral_repeat1,
    ACTIONS(21), 6,
      anon_sym_DOT,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(19), 20,
      ts_builtin_sym_end,
      anon_sym_e,
      anon_sym_E,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [87] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_decimal,
    STATE(3), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(70), 1,
      sym_exponentMark,
    ACTIONS(15), 2,
      anon_sym_e,
      anon_sym_E,
    ACTIONS(28), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(26), 18,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [131] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(34), 1,
      anon_sym_BANG,
    ACTIONS(36), 1,
      anon_sym_SLASH,
    ACTIONS(44), 1,
      anon_sym_EQ,
    STATE(38), 1,
      sym_binaryOperator,
    ACTIONS(40), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(42), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
    STATE(42), 3,
      sym_arithmeticOperator,
      sym_compareOperator,
      sym_logicOperator,
    ACTIONS(32), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(38), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(30), 8,
      ts_builtin_sym_end,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [182] = 19,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      sym_decimal,
    ACTIONS(50), 1,
      anon_sym_foo,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      anon_sym_RPAREN,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(5), 1,
      sym_expressionTerm,
    STATE(23), 1,
      sym_numericLiteral,
    STATE(41), 1,
      sym_operation,
    STATE(53), 1,
      sym_expression,
    STATE(73), 1,
      sym_arguments,
    ACTIONS(48), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(24), 2,
      sym_tuple,
      sym_object,
    STATE(40), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(62), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(35), 4,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [248] = 19,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      sym_decimal,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    ACTIONS(64), 1,
      anon_sym_foo,
    ACTIONS(66), 1,
      anon_sym_RBRACE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(5), 1,
      sym_expressionTerm,
    STATE(23), 1,
      sym_numericLiteral,
    STATE(41), 1,
      sym_operation,
    STATE(64), 1,
      sym_expression,
    STATE(67), 1,
      sym_objectElement,
    ACTIONS(48), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(24), 2,
      sym_tuple,
      sym_object,
    STATE(40), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(62), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(35), 4,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [314] = 19,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      sym_decimal,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    ACTIONS(64), 1,
      anon_sym_foo,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(5), 1,
      sym_expressionTerm,
    STATE(23), 1,
      sym_numericLiteral,
    STATE(41), 1,
      sym_operation,
    STATE(62), 1,
      sym_objectElement,
    STATE(64), 1,
      sym_expression,
    ACTIONS(48), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(24), 2,
      sym_tuple,
      sym_object,
    STATE(40), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(62), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(35), 4,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [380] = 19,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      sym_decimal,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    ACTIONS(64), 1,
      anon_sym_foo,
    ACTIONS(70), 1,
      anon_sym_RBRACE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(5), 1,
      sym_expressionTerm,
    STATE(23), 1,
      sym_numericLiteral,
    STATE(41), 1,
      sym_operation,
    STATE(64), 1,
      sym_expression,
    STATE(67), 1,
      sym_objectElement,
    ACTIONS(48), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(24), 2,
      sym_tuple,
      sym_object,
    STATE(40), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(62), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(35), 4,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [446] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      sym_decimal,
    ACTIONS(50), 1,
      anon_sym_foo,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    ACTIONS(72), 1,
      anon_sym_RBRACK,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(5), 1,
      sym_expressionTerm,
    STATE(23), 1,
      sym_numericLiteral,
    STATE(41), 1,
      sym_operation,
    STATE(58), 1,
      sym_expression,
    ACTIONS(48), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(24), 2,
      sym_tuple,
      sym_object,
    STATE(40), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(62), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(35), 4,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [509] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      sym_decimal,
    ACTIONS(50), 1,
      anon_sym_foo,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    ACTIONS(74), 1,
      anon_sym_RBRACK,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(5), 1,
      sym_expressionTerm,
    STATE(23), 1,
      sym_numericLiteral,
    STATE(41), 1,
      sym_operation,
    STATE(52), 1,
      sym_expression,
    ACTIONS(48), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(24), 2,
      sym_tuple,
      sym_object,
    STATE(40), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(62), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(35), 4,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [572] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      sym_decimal,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    ACTIONS(64), 1,
      anon_sym_foo,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(5), 1,
      sym_expressionTerm,
    STATE(23), 1,
      sym_numericLiteral,
    STATE(41), 1,
      sym_operation,
    STATE(64), 1,
      sym_expression,
    STATE(67), 1,
      sym_objectElement,
    ACTIONS(48), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(24), 2,
      sym_tuple,
      sym_object,
    STATE(40), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(62), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(35), 4,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [635] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      sym_decimal,
    ACTIONS(50), 1,
      anon_sym_foo,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    ACTIONS(76), 1,
      anon_sym_RBRACK,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(5), 1,
      sym_expressionTerm,
    STATE(23), 1,
      sym_numericLiteral,
    STATE(41), 1,
      sym_operation,
    STATE(52), 1,
      sym_expression,
    ACTIONS(48), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(24), 2,
      sym_tuple,
      sym_object,
    STATE(40), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(62), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(35), 4,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [698] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_decimal,
    STATE(3), 1,
      aux_sym_numericLiteral_repeat1,
    ACTIONS(28), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(26), 18,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [735] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      sym_decimal,
    ACTIONS(50), 1,
      anon_sym_foo,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    ACTIONS(78), 1,
      anon_sym_RPAREN,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(5), 1,
      sym_expressionTerm,
    STATE(23), 1,
      sym_numericLiteral,
    STATE(41), 1,
      sym_operation,
    STATE(52), 1,
      sym_expression,
    ACTIONS(48), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(24), 2,
      sym_tuple,
      sym_object,
    STATE(40), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(62), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(35), 4,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [798] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_decimal,
    STATE(3), 1,
      aux_sym_numericLiteral_repeat1,
    ACTIONS(82), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(80), 18,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [835] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      sym_decimal,
    ACTIONS(50), 1,
      anon_sym_foo,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    ACTIONS(84), 1,
      anon_sym_RPAREN,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(5), 1,
      sym_expressionTerm,
    STATE(23), 1,
      sym_numericLiteral,
    STATE(41), 1,
      sym_operation,
    STATE(52), 1,
      sym_expression,
    ACTIONS(48), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(24), 2,
      sym_tuple,
      sym_object,
    STATE(40), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(62), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(35), 4,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [898] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      sym_decimal,
    ACTIONS(50), 1,
      anon_sym_foo,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(5), 1,
      sym_expressionTerm,
    STATE(23), 1,
      sym_numericLiteral,
    STATE(41), 1,
      sym_operation,
    STATE(71), 1,
      sym_expression,
    ACTIONS(48), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(24), 2,
      sym_tuple,
      sym_object,
    STATE(40), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(62), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(35), 4,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [958] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      sym_decimal,
    ACTIONS(50), 1,
      anon_sym_foo,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(5), 1,
      sym_expressionTerm,
    STATE(23), 1,
      sym_numericLiteral,
    STATE(41), 1,
      sym_operation,
    STATE(66), 1,
      sym_expression,
    ACTIONS(48), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(24), 2,
      sym_tuple,
      sym_object,
    STATE(40), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(62), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(35), 4,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [1018] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      sym_decimal,
    ACTIONS(50), 1,
      anon_sym_foo,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(5), 1,
      sym_expressionTerm,
    STATE(23), 1,
      sym_numericLiteral,
    STATE(41), 1,
      sym_operation,
    STATE(52), 1,
      sym_expression,
    ACTIONS(48), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(24), 2,
      sym_tuple,
      sym_object,
    STATE(40), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(62), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(35), 4,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [1078] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      sym_decimal,
    ACTIONS(50), 1,
      anon_sym_foo,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(5), 1,
      sym_expressionTerm,
    STATE(23), 1,
      sym_numericLiteral,
    STATE(41), 1,
      sym_operation,
    STATE(75), 1,
      sym_expression,
    ACTIONS(48), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(24), 2,
      sym_tuple,
      sym_object,
    STATE(40), 2,
      sym_unaryOp,
      sym_binaryOp,
    ACTIONS(62), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(35), 4,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [1138] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(86), 18,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1169] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(90), 18,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1200] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(94), 18,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1231] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(98), 18,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1262] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(102), 18,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1293] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(106), 18,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1324] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(110), 18,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1355] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(114), 18,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1386] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(118), 18,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1417] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(122), 18,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1448] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(126), 18,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1479] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(130), 18,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1510] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(134), 18,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1541] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(138), 18,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1572] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(142), 18,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1603] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 5,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(146), 18,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_foo,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1634] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      sym_decimal,
    ACTIONS(50), 1,
      anon_sym_foo,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(23), 1,
      sym_numericLiteral,
    STATE(47), 1,
      sym_expressionTerm,
    STATE(24), 2,
      sym_tuple,
      sym_object,
    ACTIONS(62), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(35), 4,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [1680] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      sym_decimal,
    ACTIONS(50), 1,
      anon_sym_foo,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      aux_sym_numericLiteral_repeat1,
    STATE(23), 1,
      sym_numericLiteral,
    STATE(46), 1,
      sym_expressionTerm,
    STATE(24), 2,
      sym_tuple,
      sym_object,
    ACTIONS(62), 3,
      sym_true,
      sym_false,
      sym_null,
    STATE(35), 4,
      sym_functionCall,
      sym_collectionValue,
      sym_stringLiteral,
      sym_literalValue,
  [1726] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 9,
      ts_builtin_sym_end,
      anon_sym_foo,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1741] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 9,
      ts_builtin_sym_end,
      anon_sym_foo,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1756] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 9,
      sym_decimal,
      anon_sym_foo,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      sym_null,
  [1771] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 9,
      sym_decimal,
      anon_sym_foo,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      sym_null,
  [1786] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 9,
      sym_decimal,
      anon_sym_foo,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      sym_null,
  [1801] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 9,
      sym_decimal,
      anon_sym_foo,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      sym_null,
  [1816] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 9,
      ts_builtin_sym_end,
      anon_sym_foo,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1831] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 9,
      ts_builtin_sym_end,
      anon_sym_foo,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1846] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      ts_builtin_sym_end,
    ACTIONS(166), 1,
      anon_sym_foo,
    STATE(48), 3,
      sym_attribute,
      sym_block,
      aux_sym_body_repeat1,
  [1861] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_foo,
    ACTIONS(169), 1,
      ts_builtin_sym_end,
    STATE(48), 3,
      sym_attribute,
      sym_block,
      aux_sym_body_repeat1,
  [1876] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      aux_sym_arguments_repeat1,
    ACTIONS(171), 3,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
  [1891] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_RPAREN,
    ACTIONS(176), 1,
      anon_sym_COMMA,
    ACTIONS(178), 1,
      anon_sym_DOT_DOT_DOT,
    STATE(50), 1,
      aux_sym_arguments_repeat1,
  [1907] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_RBRACK,
  [1917] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_RPAREN,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    ACTIONS(184), 1,
      anon_sym_DOT_DOT_DOT,
    STATE(51), 1,
      aux_sym_arguments_repeat1,
  [1933] = 4,
    ACTIONS(186), 1,
      anon_sym_DQUOTE,
    ACTIONS(188), 1,
      aux_sym_stringLiteral_token1,
    ACTIONS(190), 1,
      sym_comment,
    STATE(63), 1,
      aux_sym_stringLiteral_repeat1,
  [1946] = 4,
    ACTIONS(190), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_DQUOTE,
    ACTIONS(194), 1,
      aux_sym_stringLiteral_token1,
    STATE(55), 1,
      aux_sym_stringLiteral_repeat1,
  [1959] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_RBRACK,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      aux_sym_arguments_repeat1,
  [1972] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    ACTIONS(202), 1,
      anon_sym_RBRACE,
    STATE(57), 1,
      aux_sym_object_repeat1,
  [1985] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_COMMA,
    ACTIONS(206), 1,
      anon_sym_RBRACK,
    STATE(56), 1,
      aux_sym_arguments_repeat1,
  [1998] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_LPAREN,
    ACTIONS(208), 2,
      anon_sym_EQ,
      anon_sym_COLON,
  [2009] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_RBRACE,
    ACTIONS(212), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      aux_sym_object_repeat1,
  [2022] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      sym_decimal,
    ACTIONS(216), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [2033] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      anon_sym_COMMA,
    ACTIONS(220), 1,
      anon_sym_RBRACE,
    STATE(60), 1,
      aux_sym_object_repeat1,
  [2046] = 4,
    ACTIONS(190), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_DQUOTE,
    ACTIONS(224), 1,
      aux_sym_stringLiteral_token1,
    STATE(55), 1,
      aux_sym_stringLiteral_repeat1,
  [2059] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 2,
      anon_sym_EQ,
      anon_sym_COLON,
  [2067] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      sym_decimal,
    STATE(4), 1,
      aux_sym_numericLiteral_repeat1,
  [2077] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2085] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2093] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      sym_decimal,
    STATE(14), 1,
      aux_sym_numericLiteral_repeat1,
  [2103] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_foo,
    ACTIONS(234), 1,
      anon_sym_EQ,
  [2113] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      sym_decimal,
    STATE(16), 1,
      aux_sym_numericLiteral_repeat1,
  [2123] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 2,
      ts_builtin_sym_end,
      anon_sym_foo,
  [2131] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 2,
      ts_builtin_sym_end,
      anon_sym_foo,
  [2139] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      anon_sym_RPAREN,
  [2146] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_RPAREN,
  [2153] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_RPAREN,
  [2160] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_RPAREN,
  [2167] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      sym_decimal,
  [2174] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_LPAREN,
  [2181] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      ts_builtin_sym_end,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 47,
  [SMALL_STATE(4)] = 87,
  [SMALL_STATE(5)] = 131,
  [SMALL_STATE(6)] = 182,
  [SMALL_STATE(7)] = 248,
  [SMALL_STATE(8)] = 314,
  [SMALL_STATE(9)] = 380,
  [SMALL_STATE(10)] = 446,
  [SMALL_STATE(11)] = 509,
  [SMALL_STATE(12)] = 572,
  [SMALL_STATE(13)] = 635,
  [SMALL_STATE(14)] = 698,
  [SMALL_STATE(15)] = 735,
  [SMALL_STATE(16)] = 798,
  [SMALL_STATE(17)] = 835,
  [SMALL_STATE(18)] = 898,
  [SMALL_STATE(19)] = 958,
  [SMALL_STATE(20)] = 1018,
  [SMALL_STATE(21)] = 1078,
  [SMALL_STATE(22)] = 1138,
  [SMALL_STATE(23)] = 1169,
  [SMALL_STATE(24)] = 1200,
  [SMALL_STATE(25)] = 1231,
  [SMALL_STATE(26)] = 1262,
  [SMALL_STATE(27)] = 1293,
  [SMALL_STATE(28)] = 1324,
  [SMALL_STATE(29)] = 1355,
  [SMALL_STATE(30)] = 1386,
  [SMALL_STATE(31)] = 1417,
  [SMALL_STATE(32)] = 1448,
  [SMALL_STATE(33)] = 1479,
  [SMALL_STATE(34)] = 1510,
  [SMALL_STATE(35)] = 1541,
  [SMALL_STATE(36)] = 1572,
  [SMALL_STATE(37)] = 1603,
  [SMALL_STATE(38)] = 1634,
  [SMALL_STATE(39)] = 1680,
  [SMALL_STATE(40)] = 1726,
  [SMALL_STATE(41)] = 1741,
  [SMALL_STATE(42)] = 1756,
  [SMALL_STATE(43)] = 1771,
  [SMALL_STATE(44)] = 1786,
  [SMALL_STATE(45)] = 1801,
  [SMALL_STATE(46)] = 1816,
  [SMALL_STATE(47)] = 1831,
  [SMALL_STATE(48)] = 1846,
  [SMALL_STATE(49)] = 1861,
  [SMALL_STATE(50)] = 1876,
  [SMALL_STATE(51)] = 1891,
  [SMALL_STATE(52)] = 1907,
  [SMALL_STATE(53)] = 1917,
  [SMALL_STATE(54)] = 1933,
  [SMALL_STATE(55)] = 1946,
  [SMALL_STATE(56)] = 1959,
  [SMALL_STATE(57)] = 1972,
  [SMALL_STATE(58)] = 1985,
  [SMALL_STATE(59)] = 1998,
  [SMALL_STATE(60)] = 2009,
  [SMALL_STATE(61)] = 2022,
  [SMALL_STATE(62)] = 2033,
  [SMALL_STATE(63)] = 2046,
  [SMALL_STATE(64)] = 2059,
  [SMALL_STATE(65)] = 2067,
  [SMALL_STATE(66)] = 2077,
  [SMALL_STATE(67)] = 2085,
  [SMALL_STATE(68)] = 2093,
  [SMALL_STATE(69)] = 2103,
  [SMALL_STATE(70)] = 2113,
  [SMALL_STATE(71)] = 2123,
  [SMALL_STATE(72)] = 2131,
  [SMALL_STATE(73)] = 2139,
  [SMALL_STATE(74)] = 2146,
  [SMALL_STATE(75)] = 2153,
  [SMALL_STATE(76)] = 2160,
  [SMALL_STATE(77)] = 2167,
  [SMALL_STATE(78)] = 2174,
  [SMALL_STATE(79)] = 2181,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_numericLiteral, 1),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_numericLiteral, 1),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_numericLiteral_repeat1, 2),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_numericLiteral_repeat1, 2),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_numericLiteral_repeat1, 2), SHIFT_REPEAT(3),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_numericLiteral, 3),
  [28] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_numericLiteral, 3),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [34] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_numericLiteral, 5),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_numericLiteral, 5),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stringLiteral, 2),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stringLiteral, 2),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literalValue, 1),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literalValue, 1),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_collectionValue, 1),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_collectionValue, 1),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stringLiteral, 3),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stringLiteral, 3),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 2),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple, 2),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 4),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 3),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 2),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 4),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple, 4),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 5),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 5),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functionCall, 4),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functionCall, 4),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 5),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple, 5),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 3),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple, 3),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expressionTerm, 1),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expressionTerm, 1),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expressionTerm, 3),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expressionTerm, 3),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functionCall, 3),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functionCall, 3),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 1),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binaryOperator, 1),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compareOperator, 1),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logicOperator, 1),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arithmeticOperator, 1),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unaryOp, 2),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binaryOp, 3),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2), SHIFT_REPEAT(69),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2), SHIFT_REPEAT(20),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 1),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_stringLiteral_repeat1, 2),
  [194] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_stringLiteral_repeat1, 2), SHIFT_REPEAT(55),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [199] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2), SHIFT_REPEAT(12),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exponentMark, 1),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_objectElement, 3),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exponentMark, 2),
  [248] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_hcl(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .field_count = FIELD_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
